# Generated by Django 2.2.1 on 2019-05-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.TextField(max_length=20, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门名称',
                'verbose_name_plural': '部门名称',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projname', models.TextField(max_length=20, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目名称',
            },
        ),
        migrations.CreateModel(
            name='Sysconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confer_type', models.CharField(max_length=30, verbose_name='会议类型')),
            ],
            options={
                'verbose_name': '系统默认项',
                'verbose_name_plural': '系统默认项',
            },
        ),
    ]
