# Generated by Django 2.2.1 on 2019-06-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confer_manage', '0002_conference_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='confer_apart',
        ),
        migrations.AddField(
            model_name='conference',
            name='confer_apart',
            field=models.ManyToManyField(default='', to='confer_manage.Apartment', verbose_name='所属部门'),
        ),
    ]
