# Generated by Django 2.2.1 on 2019-06-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confer_manage', '0003_auto_20190605_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='time',
        ),
        migrations.AddField(
            model_name='conference',
            name='endtime',
            field=models.CharField(default='', max_length=30, verbose_name='结束时间'),
        ),
    ]
