# Generated by Django 2.2.1 on 2019-06-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confer_manage', '0004_auto_20190605_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='ex_time',
        ),
    ]
