# Generated by Django 2.2.1 on 2019-06-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confer_manage', '0009_auto_20190614_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='followup',
            field=models.CharField(default='', max_length=100, verbose_name='跟踪问题'),
        ),
    ]
