# Generated by Django 2.2.1 on 2019-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confer_manage', '0010_auto_20190628_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='sentence',
            field=models.TextField(max_length=300, verbose_name='汇报内容'),
        ),
    ]
