# Generated by Django 2.2.1 on 2019-07-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_confirmstring_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(height_field=200, upload_to='../static/login/image/', width_field=200),
        ),
    ]
