# Generated by Django 2.2.1 on 2019-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190702_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='user',
            name='width',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='../static/login/image/', width_field='width'),
        ),
    ]
