# Generated by Django 2.2.1 on 2019-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190702_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='./static/login/image/', width_field='width'),
        ),
    ]
