# Generated by Django 2.2.1 on 2019-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190702_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='../static/login/image/', width_field='width'),
        ),
    ]
