# Generated by Django 2.2.1 on 2019-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190702_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='image', width_field='width'),
        ),
    ]
