# Generated by Django 2.2.1 on 2019-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190702_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='image/avatar.png', height_field='height', upload_to='image', width_field='width'),
        ),
    ]
